In [1]:
import torch

if torch.cuda.is_available():    
    
    device = torch.device("cuda")

    print('There are %d GPU(s) available.' % torch.cuda.device_count())

    print('We will use the GPU:', torch.cuda.get_device_name(0))

else:
    print('No GPU available, using the CPU instead.')
    device = torch.device("cpu")

There are 1 GPU(s) available.
We will use the GPU: Tesla P100-PCIE-16GB


In [2]:
# For @CRM add yor github token
!git clone 'https://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:x-oauth-basic@github.com/kuiper28/sadc-movie-recommender.git'

%cd sadc-movie-recommender
!git checkout ui-changes
%cd rnn_model

Cloning into 'sadc-movie-recommender'...
remote: Enumerating objects: 76, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 76 (delta 11), reused 23 (delta 7), pack-reused 46
Unpacking objects: 100% (76/76), done.
/content/sadc-movie-recommender
Branch 'ui-changes' set up to track remote branch 'ui-changes' from 'origin'.
Switched to a new branch 'ui-changes'
/content/sadc-movie-recommender/rnn_model


In [9]:
! python3 train.py

aaaaaaaaaaaaaaaaaaaaaaa [47, 800]
tensor([47])
tensor([[-0.0867, -0.0642, -0.1094,  ...,  0.0350, -0.0287, -0.0915]],
       grad_fn=<AddmmBackward0>)
train.py:101: UserWarning: torch.nn.utils.clip_grad_norm is now deprecated in favor of torch.nn.utils.clip_grad_norm_.
  torch.nn.utils.clip_grad_norm(rnn.parameters(), clip)
aaaaaaaaaaaaaaaaaaaaaaa [2403, 2916, 2105, 1909, 1223, 2772, 2168, 2500, 2312, 1779, 543, 377, 953, 1982, 141, 3827]
tensor([2403, 2916, 2105, 1909, 1223, 2772, 2168, 2500, 2312, 1779,  543,  377,
         953, 1982,  141])
tensor([[-0.7916, -0.7148, -0.7304,  ..., -0.6754, -0.6415, -0.7814],
        [-0.8037, -0.6893, -0.7154,  ..., -0.6904, -0.6217, -0.7693],
        [-0.8410, -0.6992, -0.7444,  ..., -0.7162, -0.6230, -0.7809],
        ...,
        [-0.8519, -0.7007, -0.7709,  ..., -0.7706, -0.6613, -0.7486],
        [-0.8333, -0.7258, -0.7919,  ..., -0.7498, -0.6762, -0.7655],
        [-0.8552, -0.7147, -0.8061,  ..., -0.7481, -0.6612, -0.7691]],
       grad_fn=<